#include "/Engine/Private/Common.ush"

//This struct needs to match struct FWeatherXYPointState in ComputeShaderFrontEnd.h
struct TInfo{
	int instanceId;
};

//Bound and declared in ComputeShaderDeclarations.cpp @FComputeShaderDevPluginModule (Initializer)
//Then is filled in before use in ComputeShaderFrontEnd.cpp @ExecuteInRenderThread
RWStructuredBuffer<TInfo> data;

[numthreads(1, 1, 1)]
void VS_test(uint3 ThreadId : SV_DispatchThreadID)
{
    data[0].instanceId = data[0].instanceId + 1;
}
